# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionIncluida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('\xc1rea', '\xc1rea'), ('Insumo', 'Insumo')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('atenciones', models.ManyToManyField(blank=True, to='causes.AtencionIncluida')),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TabuladorCauses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costototal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('causes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causes.Causes')),
            ],
        ),
        migrations.AddField(
            model_name='causes',
            name='intervenciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='causes.Intervencion'),
        ),
    ]
