# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_surtida', models.PositiveIntegerField()),
                ('cantidad_recetada', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudFarmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.CharField(max_length=8)),
                ('receta2', models.CharField(blank=True, max_length=8, null=True)),
                ('poliza_segpop', models.CharField(blank=True, max_length=12, null=True)),
                ('paciente', models.CharField(max_length=255)),
                ('tiposol', models.CharField(choices=[('venta', 'venta'), ('segpop', 'segpop'), ('medcontrolado', 'medcontrolado')], max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
