# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmacia', '0001_initial'),
        ('padronprofsalud', '0001_initial'),
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudfarmacia',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padronprofsalud.ProfesionalSalud'),
        ),
        migrations.AddField(
            model_name='solicitudfarmacia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemsolfarm',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.CuadroBasico'),
        ),
        migrations.AddField(
            model_name='itemsolfarm',
            name='solfarm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.SolicitudFarmacia'),
        ),
    ]
