# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadroBasico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('clave_farmacia', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('farmacia', models.BooleanField(default=False)),
                ('controlado', models.BooleanField(default=False)),
                ('causes', models.ManyToManyField(related_name='cuadrobasico_causes', to='causes.Causes')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='PresentacionMed',
            fields=[
                ('clave', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cuadrobasico',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.PresentacionMed'),
        ),
    ]
