# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamentos', '0001_initial'),
        ('causes', '0001_initial'),
        ('cies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCAUSES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='causes_cat', to='causes.Causes')),
                ('diags', models.ManyToManyField(blank=True, related_name='diags_cat', to='cies.Cie10')),
                ('meds', models.ManyToManyField(blank=True, related_name='meds_cat', to='medicamentos.CuadroBasico')),
                ('procs', models.ManyToManyField(blank=True, related_name='procs_cat', to='cies.Cie9MC')),
            ],
        ),
    ]
