# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdUrgencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=250)),
                ('turno', models.CharField(blank=True, max_length=20, null=True)),
                ('servicio', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_hora_ing', models.DateTimeField()),
                ('fecha_hora_mod', models.DateTimeField()),
            ],
        ),
    ]
