# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0001_initial'),
        ('especialidades', '0001_initial'),
        ('turnos', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('unidadesmedicas', '0001_initial'),
        ('tipoplazas', '0001_initial'),
        ('geograficos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPuesto',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesionalSalud',
            fields=[
                ('notrab', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('apaterno', models.CharField(max_length=250)),
                ('amaterno', models.CharField(max_length=250)),
                ('curp', models.CharField(max_length=18)),
                ('rfc', models.CharField(max_length=13)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('tel_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_casa', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_consul', models.CharField(blank=True, max_length=10, null=True)),
                ('ced_prof1', models.CharField(blank=True, max_length=20, null=True)),
                ('ced_prof2', models.CharField(blank=True, max_length=20, null=True)),
                ('ced_prof3', models.CharField(blank=True, max_length=20, null=True)),
                ('funcion_real', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ing', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=10)),
                ('comedor', models.BooleanField(default=False)),
                ('cons_ext', models.BooleanField(default=False)),
                ('receta', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios')),
                ('cod_pues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='padronprofsalud.CodigoPuesto')),
                ('entidad', models.ForeignKey(default='22', on_delete=django.db.models.deletion.CASCADE, to='geograficos.Entidad')),
                ('especialidad1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad1', to='especialidades.Especialidad')),
                ('especialidad2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad2', to='especialidades.Especialidad')),
                ('especialidad3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad3', to='especialidades.Especialidad')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('nacionalidad', models.ForeignKey(default='223', on_delete=django.db.models.deletion.CASCADE, to='geograficos.Nacionalidad')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio')),
                ('tipo_plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoplazas.TipoPlaza')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.Turno')),
                ('unidad_adscripcion', models.ForeignKey(default='QTSSA012935', on_delete=django.db.models.deletion.CASCADE, to='unidadesmedicas.UnidadMedica')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
