# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geograficos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedica',
            fields=[
                ('clues', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('jurisdiccion', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05')], max_length=2)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geograficos.Municipio')),
            ],
        ),
    ]
