# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('clave', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geograficos.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('clave', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('iniciales', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
